
language: csharp
mono: none

services:
  - docker

env:
  global:
    # Mount the logs from outside the container when/if running PerformanceTestInterruptible:
    - PTI_MOUNT_LOGS=ExternalLogs

  matrix:
    # Bring up a basic test within or between containers:
    - DOCK=nodocker
    - DOCK=docker PTI_MODE=OneContainer
#    - DOCK=docker PTI_MODE=TwoContainers

script:
# Need to remove the dependence on Azure Tables /
# AZURE_STORAGE_CONN_STRING if we want to do full CI in a public
# context (or find some way to use an account without leaking its auth
# info).
# In the meantime, this will just make sure that everything builds.
- ./Scripts/run_linux_ci.sh $DOCK
